### ISSUE TITLE
Suggestion for terminology update

### ISSUE THREAD

**Issue by isakb** [keeto/expectacle#7]
I think that in the documentation and code, the name `expected` and `value` may be somewhat misleading - at least it was to me when I was creating a custom matcher.

As an example on common terminology in other libraries, here from Jest's documentation:

>   expect(received).toBe(expected) // e.g.: expect(x).toBe(123)

Here, `expected` is the (constant) value that (variable) `received` must equal for the assertion to pass.

In e.g. JUnit, the terminology is consistent with Jest with regards to `expected` (although the order of the arguments is not the same as in Jest).

```
> assertEquals(expected, actual) // e.g.: assertEquals(123, x)
```
Here, `expected` is the (constant) value that (variable) `actual` must equal for the assertion to pass.

Example from Expectacle's documentation on custom matchers:

> A matcherFunction is a function that receives two arguments and returns a boolean. The first argument is the expected value (i.e., the value passed to the expect function), and the second argument is the value passed to the matcher function when called (which can be empty; more on that in a bit).

I suggest using the following terminology instead, which would be more consistent with e.g. the terminology in Jest and JUnit:

> A matcherFunction is a function that takes two arguments and returns a boolean. The first argument is the `received` value (i.e., the value of the variable passed to the expect function), and the second argument is the `expected` value - the constant passed to the matcher function when called (which can be empty; more on that in a bit). I.e. when used as `expect(received).someCustomMatcher(expected)`, the matcher function is `function someCustomMatcher(received, expected) {}`.

**Comment by keeto** [comment]
Very late reply, but this sounds reasonable!

It is a breaking change though, since it requires renaming some public properties of the `ExpectationError` but that shouldn't be a problem.
